export const TOWER_LIMITS = {
  Wall: 1000,
  Door: 160,
  SlowTrap: 48,
  ArrowTower: 24,
  CannonTower: 24,
  MeleeTower: 24,
  MagicTower: 24,
  BombTower: 24,
  GoldMine: 8,
  Harvester: 8,
  GoldStash: 1,
};

export function getInitialTowersLength() {
  return {
    Wall: 0,
    Door: 0,
    SlowTrap: 0,
    ArrowTower: 0,
    CannonTower: 0,
    MeleeTower: 0,
    MagicTower: 0,
    BombTower: 0,
    GoldMine: 0,
    Harvester: 0,
    GoldStash: 0,
  };
}

export function getInitialConnectPacketData(playerUid) {
  return {
    allowed: 1,
    chatChannel: 0,
    effectiveDisplayName: "Player",
    effectiveTickRate: 20,
    maxPlayers: 40,
    opcode: 4,
    players: 1,
    startingTick: 0,
    tickRate: 20,
    uid: playerUid,
    x1: 0,
    x2: 24000,
    y1: 0,
    y2: 24000,
  };
}

export function getInitialPlayerData(playerUid) {
  return {
    aimingYaw: 0,
    availableSkillPoints: 1,
    baseSpeed: 37.5,
    collisionRadius: 27,
    damage: 10,
    dead: 0,
    energy: 0,
    energyRegenerationRate: 0,
    entityClass: "PlayerEntity",
    experience: 0,
    firingTick: 0,
    gold: 0,
    hatName: "",
    health: 500,
    height: 32,
    isBuildingWalking: 0,
    isInvulnerable: 1,
    isPaused: 0,
    kills: 0,
    lastDamage: 0,
    lastDamageTarget: 0,
    lastDamageTick: 0,
    lastPetDamage: 0,
    lastPetDamageTarget: 0,
    lastPetDamageTick: 0,
    level: 1,
    maxEnergy: 0,
    maxHealth: 500,
    model: "GamePlayer",
    msBetweenFires: 300,
    name: "Player",
    partyId: 1,
    petUid: 0,
    position: {
      x: window.customSpawnPoint ? window.customSpawnPoint.x : 24000 / 2,
      y: window.customSpawnPoint ? window.customSpawnPoint.y : 24000 / 2,
    },
    reconnectSecret: "",
    score: 0,
    slowed: 0,
    speedAttribute: 0,
    startChargingTick: 0,
    stone: 0,
    stunned: 0,
    timeDead: 0,
    token: 0,
    uid: playerUid,
    wave: 0,
    weaponName: "Pickaxe",
    weaponTier: 1,
    width: 32,
    wood: 0,
    yaw: 1,
    zombieShieldHealth: 0,
    zombieShieldMaxHealth: 0,
  };
}
